# Frontend 빌드 단계
FROM node:14-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

# Nginx 서빙 단계
FROM nginx:alpine
RUN apk add --no-cache tzdata
ENV TZ=Asia/Seoul
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]