FROM maven:3.8.1-openjdk-17 as maven_build
WORKDIR /app
COPY pom.xml .
COPY src ./src
COPY src/main/resources/properties/env.properties ./src/main/resources/properties/
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim
COPY --from=maven_build /app/target/*.jar /app/app.jar
COPY --from=maven_build /app/src/main/resources/properties/env.properties /app/
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]